#!/bin/bash

# Copied from: https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [ -f "/usr/local/bin/mas" ]; then
    if ! mas account; then
        echo '`mas` has issues with fullscreen terminals.  Make sure you are not fullscreen.'
        echo
        echo 'If you are not fullscreen, please sign in with `mas` and try again.'
        echo '$ mas signin --dialog <AppleId>'
        exit
    fi
fi

LOCAL_BREWFILE="$HOME/.Brewfile.local"
[[ ! -f $LOCAL_BREWFILE ]] && LOCAL_BREWFILE=""

cat $DIR/../Brewfile.d/* $LOCAL_BREWFILE > $HOME/.Brewfile
brew bundle --global
